package contacts_test

import (
    "github.com/pomack/jsonhelper.go/jsonhelper"
    "github.com/pomack/oauth2_client.go/oauth2_client"
    "github.com/pomack/contacts.go/google"
    "github.com/pomack/dsocial.go/backend/contacts"
    "github.com/pomack/dsocial.go/backend/datastore"
    dm "github.com/pomack/dsocial.go/models/dsocial"
    "bytes"
    "json"
    "testing"
    "time"
)

const (
    GROUPS_ALL = `
    {
        "version":"1.0",
        "encoding":"UTF-8",
        "feed":
        {
            "xmlns":"http://www.w3.org/2005/Atom",
            "xmlns$openSearch":"http://a9.com/-/spec/opensearchrss/1.0/",
            "xmlns$gContact":"http://schemas.google.com/contact/2008",
            "xmlns$batch":"http://schemas.google.com/gdata/batch",
            "xmlns$gd":"http://schemas.google.com/g/2005",
            "id":
            {
                "$t":"test@example.com"
            },
            "updated":
            {
                "$t":"2011-10-28T01:50:14.713Z"
            },
            "category":
            [
                {
                    "scheme":"http://schemas.google.com/g/2005#kind",
                    "term":"http://schemas.google.com/contact/2008#group"
                }
            ],
            "title":
            {
                "type":"text",
                "$t":"John's Contact Groups"
            },
            "link":
            [
                {
                    "rel":"alternate",
                    "type":"text/html",
                    "href":"http://www.google.com/"
                },
                {
                    "rel":"http://schemas.google.com/g/2005#feed",
                    "type":"application/atom+xml",
                    "href":"https://www.google.com/m8/feeds/groups/test%40example.com/full"
                },
                {
                    "rel":"http://schemas.google.com/g/2005#post",
                    "type":"application/atom+xml",
                    "href":"https://www.google.com/m8/feeds/groups/test%40example.com/full"
                },
                {
                    "rel":"http://schemas.google.com/g/2005#batch",
                    "type":"application/atom+xml",
                    "href":"https://www.google.com/m8/feeds/groups/test%40example.com/full/batch"
                },
                {
                    "rel":"self",
                    "type":"application/atom+xml",
                    "href":"https://www.google.com/m8/feeds/groups/test%40example.com/full?alt\u003djson\u0026max-results\u003d25"
                }
            ],
            "author":
            [
                {
                    "name":
                    {
                        "$t":"John"
                    },
                    "email":
                    {
                        "$t":"test@example.com"
                    }
                }
            ],
            "generator":
            {
                "version":"1.0",
                "uri":"http://www.google.com/m8/feeds",
                "$t":"Contacts"
            },
            "openSearch$totalResults":
            {
                "$t":"12"
            },
            "openSearch$startIndex":
            {
                "$t":"1"
            },
            "openSearch$itemsPerPage":
            {
                "$t":"25"
            },
            "entry":
            [
                {
                    "id":
                    {
                        "$t":"http://www.google.com/m8/feeds/groups/test%40example.com/base/d1e92609e11920"
                    },
                    "updated":
                    {
                        "$t":"2008-12-09T21:22:01.339Z"
                    },
                    "category":
                    [
                        {
                            "scheme":"http://schemas.google.com/g/2005#kind",
                            "term":"http://schemas.google.com/contact/2008#group"
                        }
                    ],
                    "title":
                    {
                        "type":"text",
                        "$t":"Scientists"
                    },
                    "content":
                    {
                        "type":"text",
                        "$t":"Scientists"
                    },
                    "link":
                    [
                        {
                            "rel":"self",
                            "type":"application/atom+xml",
                            "href":"https://www.google.com/m8/feeds/groups/test%40example.com/full/d1e92609e11920"
                        },
                        {
                            "rel":"edit",
                            "type":"application/atom+xml",
                            "href":"https://www.google.com/m8/feeds/groups/test%40example.com/full/d1e92609e11920/1228857721339000"
                        }
                    ]
                },
                {
                    "id":
                    {
                        "$t":"http://www.google.com/m8/feeds/groups/test%40example.com/base/94003eb8a1a2e03"
                    },
                    "updated":
                    {
                        "$t":"2008-09-10T23:03:05.447Z"
                    },
                    "category":
                    [
                        {
                            "scheme":"http://schemas.google.com/g/2005#kind",
                            "term":"http://schemas.google.com/contact/2008#group"
                        }
                    ],
                    "title":
                    {
                        "type":"text",
                        "$t":"Heads of State"
                    },
                    "content":
                    {
                        "type":"text",
                        "$t":"Heads of State"
                    },
                    "link":
                    [
                        {
                            "rel":"self",
                            "type":"application/atom+xml",
                            "href":"https://www.google.com/m8/feeds/groups/test%40example.com/full/94003eb8a1a2e03"
                        },
                        {
                            "rel":"edit",
                            "type":"application/atom+xml",
                            "href":"https://www.google.com/m8/feeds/groups/test%40example.com/full/94003eb8a1a2e03/1221087785447000"
                        }
                    ]
                },
                {
                    "id":
                    {
                        "$t":"http://www.google.com/m8/feeds/groups/test%40example.com/base/1795f0918fd30f5d"
                    },
                    "updated":
                    {
                        "$t":"2009-02-16T18:45:14.938Z"
                    },
                    "category":
                    [
                        {
                            "scheme":"http://schemas.google.com/g/2005#kind",
                            "term":"http://schemas.google.com/contact/2008#group"
                        }
                    ],
                    "title":
                    {
                        "type":"text",
                        "$t":"Generals"
                    },
                    "content":
                    {
                        "type":"text",
                        "$t":"Generals"
                    },
                    "link":
                    [
                        {
                            "rel":"self",
                            "type":"application/atom+xml",
                            "href":"https://www.google.com/m8/feeds/groups/test%40example.com/full/1795f0918fd30f5d"
                        },
                        {
                            "rel":"edit",
                            "type":"application/atom+xml",
                            "href":"https://www.google.com/m8/feeds/groups/test%40example.com/full/1795f0918fd30f5d/1234809914938000"
                        }
                    ]
                },
                {
                    "id":
                    {
                        "$t":"http://www.google.com/m8/feeds/groups/test%40example.com/base/1996b7e58fdedad6"
                    },
                    "updated":
                    {
                        "$t":"2010-12-22T21:01:12.783Z"
                    },
                    "category":
                    [
                        {
                            "scheme":"http://schemas.google.com/g/2005#kind",
                            "term":"http://schemas.google.com/contact/2008#group"
                        }
                    ],
                    "title":
                    {
                        "type":"text",
                        "$t":"Business Leaders"
                    },
                    "content":
                    {
                        "type":"text",
                        "$t":"Business Leaders"
                    },
                    "link":
                    [
                        {
                            "rel":"self",
                            "type":"application/atom+xml",
                            "href":"https://www.google.com/m8/feeds/groups/test%40example.com/full/1996b7e58fdedad6"
                        },
                        {
                            "rel":"edit",
                            "type":"application/atom+xml",
                            "href":"https://www.google.com/m8/feeds/groups/test%40example.com/full/1996b7e58fdedad6/1293051672783000"
                        }
                    ]
                },
                {
                    "id":
                    {
                        "$t":"http://www.google.com/m8/feeds/groups/test%40example.com/base/19dc93f30c4d3d84"
                    },
                    "updated":
                    {
                        "$t":"2010-11-13T04:55:42.986Z"
                    },
                    "category":
                    [
                        {
                            "scheme":"http://schemas.google.com/g/2005#kind",
                            "term":"http://schemas.google.com/contact/2008#group"
                        }
                    ],
                    "title":
                    {
                        "type":"text",
                        "$t":"Historians"
                    },
                    "content":
                    {
                        "type":"text",
                        "$t":"Historians"
                    },
                    "link":
                    [
                        {
                            "rel":"self",
                            "type":"application/atom+xml",
                            "href":"https://www.google.com/m8/feeds/groups/test%40example.com/full/19dc93f30c4d3d84"
                        },
                        {
                            "rel":"edit",
                            "type":"application/atom+xml",
                            "href":"https://www.google.com/m8/feeds/groups/test%40example.com/full/19dc93f30c4d3d84/1289624142986000"
                        }
                    ]
                },
                {
                    "id":
                    {
                        "$t":"http://www.google.com/m8/feeds/groups/test%40example.com/base/1a9d09068c2ecbd5"
                    },
                    "updated":
                    {
                        "$t":"2010-02-05T18:15:50.378Z"
                    },
                    "category":
                    [
                        {
                            "scheme":"http://schemas.google.com/g/2005#kind",
                            "term":"http://schemas.google.com/contact/2008#group"
                        }
                    ],
                    "title":
                    {
                        "type":"text",
                        "$t":"Technologists"
                    },
                    "content":
                    {
                        "type":"text",
                        "$t":"Technologists"
                    },
                    "link":
                    [
                        {
                            "rel":"self",
                            "type":"application/atom+xml",
                            "href":"https://www.google.com/m8/feeds/groups/test%40example.com/full/1a9d09068c2ecbd5"
                        },
                        {
                            "rel":"edit",
                            "type":"application/atom+xml",
                            "href":"https://www.google.com/m8/feeds/groups/test%40example.com/full/1a9d09068c2ecbd5/1265393750378000"
                        }
                    ]
                },
                {
                    "id":
                    {
                        "$t":"http://www.google.com/m8/feeds/groups/test%40example.com/base/28864c188a67ceb4"
                    },
                    "updated":
                    {
                        "$t":"2011-03-05T20:27:56.247Z"
                    },
                    "category":
                    [
                        {
                            "scheme":"http://schemas.google.com/g/2005#kind",
                            "term":"http://schemas.google.com/contact/2008#group"
                        }
                    ],
                    "title":
                    {
                        "type":"text",
                        "$t":"Teachers"
                    },
                    "content":
                    {
                        "type":"text",
                        "$t":"Teachers"
                    },
                    "link":
                    [
                        {
                            "rel":"self",
                            "type":"application/atom+xml",
                            "href":"https://www.google.com/m8/feeds/groups/test%40example.com/full/28864c188a67ceb4"
                        },
                        {
                            "rel":"edit",
                            "type":"application/atom+xml",
                            "href":"https://www.google.com/m8/feeds/groups/test%40example.com/full/28864c188a67ceb4/1299356876247000"
                        }
                    ]
                },
                {
                    "id":
                    {
                        "$t":"http://www.google.com/m8/feeds/groups/test%40example.com/base/3bf3b6eb8f242977"
                    },
                    "updated":
                    {
                        "$t":"2009-05-27T00:16:03.533Z"
                    },
                    "category":
                    [
                        {
                            "scheme":"http://schemas.google.com/g/2005#kind",
                            "term":"http://schemas.google.com/contact/2008#group"
                        }
                    ],
                    "title":
                    {
                        "type":"text",
                        "$t":"Anarchists"
                    },
                    "content":
                    {
                        "type":"text",
                        "$t":"Anarchists"
                    },
                    "link":
                    [
                        {
                            "rel":"self",
                            "type":"application/atom+xml",
                            "href":"https://www.google.com/m8/feeds/groups/test%40example.com/full/3bf3b6eb8f242977"
                        },
                        {
                            "rel":"edit",
                            "type":"application/atom+xml",
                            "href":"https://www.google.com/m8/feeds/groups/test%40example.com/full/3bf3b6eb8f242977/1243383363533000"
                        }
                    ]
                },
                {
                    "id":
                    {
                        "$t":"http://www.google.com/m8/feeds/groups/test%40example.com/base/4c9d3b400c1cbf40"
                    },
                    "updated":
                    {
                        "$t":"2008-12-09T04:59:11.891Z"
                    },
                    "category":
                    [
                        {
                            "scheme":"http://schemas.google.com/g/2005#kind",
                            "term":"http://schemas.google.com/contact/2008#group"
                        }
                    ],
                    "title":
                    {
                        "type":"text",
                        "$t":"Friends"
                    },
                    "content":
                    {
                        "type":"text",
                        "$t":"Friends"
                    },
                    "link":
                    [
                        {
                            "rel":"self",
                            "type":"application/atom+xml",
                            "href":"https://www.google.com/m8/feeds/groups/test%40example.com/full/4c9d3b400c1cbf40"
                        },
                        {
                            "rel":"edit",
                            "type":"application/atom+xml",
                            "href":"https://www.google.com/m8/feeds/groups/test%40example.com/full/4c9d3b400c1cbf40/1228798751891000"
                        }
                    ]
                },
                {
                    "id":
                    {
                        "$t":"http://www.google.com/m8/feeds/groups/test%40example.com/base/60777f150a24f5b9"
                    },
                    "updated":
                    {
                        "$t":"2009-02-16T18:44:26.988Z"
                    },
                    "category":
                    [
                        {
                            "scheme":"http://schemas.google.com/g/2005#kind",
                            "term":"http://schemas.google.com/contact/2008#group"
                        }
                    ],
                    "title":
                    {
                        "type":"text",
                        "$t":"College Friends"
                    },
                    "content":
                    {
                        "type":"text",
                        "$t":"College Friends"
                    },
                    "link":
                    [
                        {
                            "rel":"self",
                            "type":"application/atom+xml",
                            "href":"https://www.google.com/m8/feeds/groups/test%40example.com/full/60777f150a24f5b9"
                        },
                        {
                            "rel":"edit",
                            "type":"application/atom+xml",
                            "href":"https://www.google.com/m8/feeds/groups/test%40example.com/full/60777f150a24f5b9/1234809866988000"
                        }
                    ]
                },
                {
                    "id":
                    {
                        "$t":"http://www.google.com/m8/feeds/groups/test%40example.com/base/671fd3d70931631e"
                    },
                    "updated":
                    {
                        "$t":"2010-03-03T05:04:34.785Z"
                    },
                    "category":
                    [
                        {
                            "scheme":"http://schemas.google.com/g/2005#kind",
                            "term":"http://schemas.google.com/contact/2008#group"
                        }
                    ],
                    "title":
                    {
                        "type":"text",
                        "$t":"Acquaintances"
                    },
                    "content":
                    {
                        "type":"text",
                        "$t":"Acquaintances"
                    },
                    "link":
                    [
                        {
                            "rel":"self",
                            "type":"application/atom+xml",
                            "href":"https://www.google.com/m8/feeds/groups/test%40example.com/full/671fd3d70931631e"
                        },
                        {
                            "rel":"edit",
                            "type":"application/atom+xml",
                            "href":"https://www.google.com/m8/feeds/groups/test%40example.com/full/671fd3d70931631e/1267592674785000"
                        }
                    ]
                },
                {
                    "id":
                    {
                        "$t":"http://www.google.com/m8/feeds/groups/test%40example.com/base/7a2e56b70df44baf"
                    },
                    "updated":
                    {
                        "$t":"2010-06-13T21:51:36.871Z"
                    },
                    "category":
                    [
                        {
                            "scheme":"http://schemas.google.com/g/2005#kind",
                            "term":"http://schemas.google.com/contact/2008#group"
                        }
                    ],
                    "title":
                    {
                        "type":"text",
                        "$t":"Family"
                    },
                    "content":
                    {
                        "type":"text",
                        "$t":"Family"
                    },
                    "link":
                    [
                        {
                            "rel":"self",
                            "type":"application/atom+xml",
                            "href":"https://www.google.com/m8/feeds/groups/test%40example.com/full/7a2e56b70df44baf"
                        },
                        {
                            "rel":"edit",
                            "type":"application/atom+xml",
                            "href":"https://www.google.com/m8/feeds/groups/test%40example.com/full/7a2e56b70df44baf/1276465896871000"
                        }
                    ]
                }
            ]
        }
    }`
    
    
    CONTACT_GEORGE_WASHINGTON = `
    {
        "version":"1.0",
        "encoding":"UTF-8",
        "entry":
        {
            "xmlns":"http://www.w3.org/2005/Atom",
            "xmlns$gContact":"http://schemas.google.com/contact/2008",
            "xmlns$batch":"http://schemas.google.com/gdata/batch",
            "xmlns$gd":"http://schemas.google.com/g/2005",
            "gd$etag":"\"SHczfOIJLit7I2A9WhdaFksNQQQ.\"",
            "id":
            {
                "$t":"http://www.google.com/m8/feeds/contacts/test%40example.com/base/49d4ef73456137d3"
            },
            "updated":
            {
                "$t":"2011-10-26T22:20:09.985Z"
            },
            "app$edited":
            {
                "xmlns$app":"http://www.w3.org/2007/app",
                "$t":"2011-10-26T22:20:09.985Z"
            },
            "category":
            [
                {
                    "scheme":"http://schemas.google.com/g/2005#kind",
                    "term":"http://schemas.google.com/contact/2008#contact"
                }
            ],
            "title":
            {
                "$t":"George Washington"
            },
            "content":
            {
                "$t":"1st President of the US\nCommander in the Revolutionary War"
            },
            "link":
            [
                {
                    "rel":"http://schemas.google.com/contacts/2008/rel#photo",
                    "type":"image/*",
                    "href":"https://www.google.com/m8/feeds/photos/media/test%40example.com/49d4ef73456137d3",
                    "gd$etag":"\"Zh5uNHQASit7I2A0OE4sdfpcHG0fG2IYVQM.\""
                },
                {
                    "rel":"self",
                    "type":"application/atom+xml",
                    "href":"https://www.google.com/m8/feeds/contacts/test%40example.com/full/49d4ef73456137d3"
                },
                {
                    "rel":"edit",
                    "type":"application/atom+xml",
                    "href":"https://www.google.com/m8/feeds/contacts/test%40example.com/full/49d4ef73456137d3/1319667609985001"
                }
            ],
            "gd$name":
            {
                "gd$fullName":
                {
                    "$t":"George Washington"
                },
                "gd$givenName":
                {
                    "$t":"George"
                },
                "gd$familyName":
                {
                    "$t":"Washington"
                }
            },
            "gContact$nickname":
            {
                "$t":"George"
            },
            "gContact$birthday":
            {
                "when":"1732-02-22"
            },
            "gContact$event":
            [
                {
                    "label":"death",
                    "gd$when":
                    {
                        "startTime":"1799-12-14"
                    }
                },
                {
                    "rel":"anniversary",
                    "gd$when":
                    {
                        "startTime":"1759-01-06"
                    }
                }
            ],
            "gd$organization":
            [
                {
                    "rel":"http://schemas.google.com/g/2005#work",
                    "gd$orgName":
                    {
                        "$t":"United States of America Federal Government"
                    },
                    "gd$orgTitle":
                    {
                        "$t":"President of the United States"
                    }
                }
            ],
            "gd$email":
            [
                {
                    "rel":"http://schemas.google.com/g/2005#home",
                    "address":"gw@example.com",
                    "primary":"true"
                },
                {
                    "rel":"http://schemas.google.com/g/2005#work",
                    "address":"george.washington@whitehouse.gov"
                },
                {
                    "label":"Old Work",
                    "address":"potus@whitehouse.gov"
                }
            ],
            "gd$im":
            [
                {
                    "address":"georgewashington@hotmail.com",
                    "protocol":"http://schemas.google.com/g/2005#MSN",
                    "rel":"http://schemas.google.com/g/2005#other"
                },
                {
                    "address":"gw",
                    "protocol":"http://schemas.google.com/g/2005#AIM",
                    "rel":"http://schemas.google.com/g/2005#other"
                },
                {
                    "address":"george",
                    "protocol":"http://schemas.google.com/g/2005#YAHOO",
                    "rel":"http://schemas.google.com/g/2005#other"
                },
                {
                    "address":"potus",
                    "protocol":"http://schemas.google.com/g/2005#AIM",
                    "rel":"http://schemas.google.com/g/2005#other"
                },
                {
                    "address":"12432",
                    "protocol":"http://schemas.google.com/g/2005#ICQ",
                    "rel":"http://schemas.google.com/g/2005#other"
                },
                {
                    "address":"gw",
                    "protocol":"http://schemas.google.com/g/2005#GOOGLE_TALK",
                    "rel":"http://schemas.google.com/g/2005#other"
                }
            ],
            "gd$phoneNumber":
            [
                {
                    "rel":"http://schemas.google.com/g/2005#mobile",
                    "$t":"+1-202-555-1111"
                },
                {
                    "rel":"http://schemas.google.com/g/2005#home_fax",
                    "$t":"+1-202-555-2222"
                },
                {
                    "rel":"http://schemas.google.com/g/2005#home",
                    "$t":"+1-202-555-3333"
                },
                {
                    "rel":"http://schemas.google.com/g/2005#work",
                    "$t":"+1-202-555-4444"
                }
            ],
            "gd$structuredPostalAddress":
            [
                {
                    "rel":"http://schemas.google.com/g/2005#home",
                    "gd$formattedAddress":
                    {
                        "$t":"524-30 Market Street\nPhiladelphia, PA 19106\nUnited States"
                    },
                    "gd$street":
                    {
                        "$t":"524-30 Market Street"
                    },
                    "gd$postcode":
                    {
                        "$t":"19106"
                    },
                    "gd$city":
                    {
                        "$t":"Philadelphia"
                    },
                    "gd$region":
                    {
                        "$t":"PA"
                    },
                    "gd$country":
                    {
                        "$t":"United States"
                    }
                },
                {
                    "rel":"http://schemas.google.com/g/2005#work",
                    "gd$formattedAddress":
                    {
                        "$t":"524-30 Market Street\nPhiladelphia, PA 19106\nUnited States"
                    },
                    "gd$street":
                    {
                        "$t":"524-30 Market Street"
                    },
                    "gd$postcode":
                    {
                        "$t":"19106"
                    },
                    "gd$city":
                    {
                        "$t":"Philadelphia"
                    },
                    "gd$region":
                    {
                        "$t":"PA"
                    },
                    "gd$country":
                    {
                        "$t":"United States"
                    }
                },
                {
                    "rel":"http://schemas.google.com/g/2005#other",
                    "gd$formattedAddress":
                    {
                        "$t":"Mount Vernon, VA\nUSA"
                    },
                    "gd$city":
                    {
                        "$t":"Mount Vernon"
                    },
                    "gd$region":
                    {
                        "$t":"VA"
                    },
                    "gd$country":
                    {
                        "code":"US",
                        "$t":"USA"
                    }
                }
            ],
            "gContact$relation":
            [
                {
                    "rel":"father",
                    "$t":"Augustine Washington"
                },
                {
                    "rel":"mother",
                    "$t":"Mary Ball Washington"
                },
                {
                    "rel":"sister",
                    "$t":"Mildred Washington"
                },
                {
                    "rel":"brother",
                    "$t":"Butler Washington"
                },
                {
                    "rel":"sister",
                    "$t":"Jane Washington"
                },
                {
                    "rel":"brother",
                    "$t":"Lawrence Washington"
                },
                {
                    "rel":"brother",
                    "$t":"Augustine Washington"
                },
                {
                    "rel":"brother",
                    "$t":"Samuel Washington"
                },
                {
                    "rel":"sister",
                    "$t":"Elizabeth Washington"
                },
                {
                    "rel":"brother",
                    "$t":"John Augustine Washington"
                },
                {
                    "rel":"brother",
                    "$t":"Charles Washington"
                }
            ],
            "gContact$website":
            [
                {
                    "href":"http://www.whitehouse.gov/about/presidents/georgewashington",
                    "rel":"home-page"
                },
                {
                    "href":"http://www.whitehouse.gov/",
                    "rel":"work"
                }
            ],
            "gContact$groupMembershipInfo":
            [
                {
                    "deleted":"false",
                    "href":"http://www.google.com/m8/feeds/groups/test%40example.com/base/94003eb8a1a2e03"
                },
                {
                    "deleted":"false",
                    "href":"http://www.google.com/m8/feeds/groups/test%40example.com/base/1795f0918fd30f5d"
                }
            ]
        }
    }`
    
    
    CONTACT_JOHN_ADAMS = `
    {
        "version":"1.0",
        "encoding":"UTF-8",
        "entry":
        {
            "xmlns":"http://www.w3.org/2005/Atom",
            "xmlns$gContact":"http://schemas.google.com/contact/2008",
            "xmlns$batch":"http://schemas.google.com/gdata/batch",
            "xmlns$gd":"http://schemas.google.com/g/2005",
            "gd$etag":"\"SHczflijLit7I2A9WhdaFksNQQQ.\"",
            "id":
            {
                "$t":"http://www.google.com/m8/feeds/contacts/test%40example.com/base/49d4ef73466137d3"
            },
            "updated":
            {
                "$t":"2011-10-26T22:20:09.985Z"
            },
            "app$edited":
            {
                "xmlns$app":"http://www.w3.org/2007/app",
                "$t":"2011-10-26T22:20:09.985Z"
            },
            "category":
            [
                {
                    "scheme":"http://schemas.google.com/g/2005#kind",
                    "term":"http://schemas.google.com/contact/2008#contact"
                }
            ],
            "title":
            {
                "$t":"John Adams"
            },
            "content":
            {
                "$t":"2nd President of the US"
            },
            "link":
            [
                {
                    "rel":"http://schemas.google.com/contacts/2008/rel#photo",
                    "type":"image/*",
                    "href":"https://www.google.com/m8/feeds/photos/media/test%40example.com/49d4ef73466137d3",
                    "gd$etag":"\"Zh5uNHQASsfwI2A0OE4mdxpcHG0fG2IYVQM.\""
                },
                {
                    "rel":"self",
                    "type":"application/atom+xml",
                    "href":"https://www.google.com/m8/feeds/contacts/test%40example.com/full/49d4ef73466137d3"
                },
                {
                    "rel":"edit",
                    "type":"application/atom+xml",
                    "href":"https://www.google.com/m8/feeds/contacts/test%40example.com/full/49d4ef73466137d3/1319667609985001"
                }
            ],
            "gd$name":
            {
                "gd$fullName":
                {
                    "$t":"John Adams"
                },
                "gd$givenName":
                {
                    "$t":"John"
                },
                "gd$familyName":
                {
                    "$t":"Adams"
                }
            },
            "gContact$nickname":
            {
                "$t":"John"
            },
            "gContact$birthday":
            {
                "when":"1735-10-30"
            },
            "gContact$event":
            [
                {
                    "label":"death",
                    "gd$when":
                    {
                        "startTime":"1826-07-04"
                    }
                },
                {
                    "rel":"anniversary",
                    "gd$when":
                    {
                        "startTime":"1764-10-25"
                    }
                }
            ],
            "gd$organization":
            [
                {
                    "rel":"http://schemas.google.com/g/2005#work",
                    "gd$orgName":
                    {
                        "$t":"United States of America Federal Government"
                    },
                    "gd$orgTitle":
                    {
                        "$t":"President of the United States"
                    }
                }
            ],
            "gd$email":
            [
                {
                    "rel":"http://schemas.google.com/g/2005#home",
                    "address":"ja@example.com",
                    "primary":"true"
                },
                {
                    "rel":"http://schemas.google.com/g/2005#work",
                    "address":"john.adams@whitehouse.gov"
                },
                {
                    "label":"Old Work",
                    "address":"potus@whitehouse.gov"
                }
            ],
            "gd$im":
            [
                {
                    "address":"johnadams@hotmail.com",
                    "protocol":"http://schemas.google.com/g/2005#MSN",
                    "rel":"http://schemas.google.com/g/2005#other"
                },
                {
                    "address":"ja",
                    "protocol":"http://schemas.google.com/g/2005#AIM",
                    "rel":"http://schemas.google.com/g/2005#other"
                },
                {
                    "address":"john",
                    "protocol":"http://schemas.google.com/g/2005#YAHOO",
                    "rel":"http://schemas.google.com/g/2005#other"
                },
                {
                    "address":"potus",
                    "protocol":"http://schemas.google.com/g/2005#AIM",
                    "rel":"http://schemas.google.com/g/2005#other"
                },
                {
                    "address":"12467",
                    "protocol":"http://schemas.google.com/g/2005#ICQ",
                    "rel":"http://schemas.google.com/g/2005#other"
                },
                {
                    "address":"ja",
                    "protocol":"http://schemas.google.com/g/2005#GOOGLE_TALK",
                    "rel":"http://schemas.google.com/g/2005#other"
                }
            ],
            "gd$phoneNumber":
            [
                {
                    "rel":"http://schemas.google.com/g/2005#mobile",
                    "$t":"+1-202-554-1111"
                },
                {
                    "rel":"http://schemas.google.com/g/2005#home_fax",
                    "$t":"+1-202-554-2222"
                },
                {
                    "rel":"http://schemas.google.com/g/2005#home",
                    "$t":"+1-202-554-3333"
                },
                {
                    "rel":"http://schemas.google.com/g/2005#work",
                    "$t":"+1-202-554-4444"
                }
            ],
            "gd$structuredPostalAddress":
            [
                {
                    "rel":"http://schemas.google.com/g/2005#home",
                    "gd$formattedAddress":
                    {
                        "$t":"1600 Pennsylvania NW\nWashington, DC 20500\nUnited States"
                    },
                    "gd$street":
                    {
                        "$t":"1600 Pennsylvania NW"
                    },
                    "gd$postcode":
                    {
                        "$t":"20500"
                    },
                    "gd$city":
                    {
                        "$t":"Washington"
                    },
                    "gd$region":
                    {
                        "$t":"DC"
                    },
                    "gd$country":
                    {
                        "$t":"United States"
                    }
                },
                {
                    "rel":"http://schemas.google.com/g/2005#work",
                    "gd$formattedAddress":
                    {
                        "$t":"1600 Pennsylvania NW\nWashington, DC 20500\nUnited States"
                    },
                    "gd$street":
                    {
                        "$t":"1600 Pennsylvania NW"
                    },
                    "gd$postcode":
                    {
                        "$t":"20500"
                    },
                    "gd$city":
                    {
                        "$t":"Washington"
                    },
                    "gd$region":
                    {
                        "$t":"DC"
                    },
                    "gd$country":
                    {
                        "$t":"United States"
                    }
                },
                {
                    "rel":"http://schemas.google.com/g/2005#other",
                    "gd$formattedAddress":
                    {
                        "$t":"Quincy, MA\nUSA"
                    },
                    "gd$city":
                    {
                        "$t":"Quincy"
                    },
                    "gd$region":
                    {
                        "$t":"MA"
                    },
                    "gd$country":
                    {
                        "code":"US",
                        "$t":"USA"
                    }
                }
            ],
            "gContact$relation":
            [
                {
                    "rel":"father",
                    "$t":"John Adams, Sr."
                },
                {
                    "rel":"mother",
                    "$t":"Susanna Boylston Adams"
                },
                {
                    "rel":"spouse",
                    "$t":"Abigail Smith"
                },
                {
                    "rel":"child",
                    "$t":"Nabby Adams"
                },
                {
                    "rel":"child",
                    "$t":"John Quincy Adams"
                },
                {
                    "rel":"child",
                    "$t":"Susanna Adams"
                },
                {
                    "rel":"child",
                    "$t":"Charles Adams"
                },
                {
                    "rel":"child",
                    "$t":"Thomas Adams"
                },
                {
                    "rel":"child",
                    "$t":"Elizabeth Adams"
                }
            ],
            "gContact$website":
            [
                {
                    "href":"http://www.whitehouse.gov/about/presidents/johnadams",
                    "rel":"home-page"
                },
                {
                    "href":"http://www.whitehouse.gov",
                    "rel":"work"
                }
            ],
            "gContact$groupMembershipInfo":
            [
                {
                    "deleted":"false",
                    "href":"http://www.google.com/m8/feeds/groups/test%40example.com/base/94003eb8a1a2e03"
                }
            ]
        }
    }`
    
    
    CONTACT_MARIE_CURIE = `
    {
        "version":"1.0",
        "encoding":"UTF-8",
        "entry":
        {
            "xmlns":"http://www.w3.org/2005/Atom",
            "xmlns$gContact":"http://schemas.google.com/contact/2008",
            "xmlns$batch":"http://schemas.google.com/gdata/batch",
            "xmlns$gd":"http://schemas.google.com/g/2005",
            "gd$etag":"\"SHczflijLit7I2A9WhdaFksNQQQ.\"",
            "id":
            {
                "$t":"http://www.google.com/m8/feeds/contacts/test%40example.com/base/49d4ef73476137d3"
            },
            "updated":
            {
                "$t":"2011-10-26T22:20:09.985Z"
            },
            "app$edited":
            {
                "xmlns$app":"http://www.w3.org/2007/app",
                "$t":"2011-10-26T22:20:09.985Z"
            },
            "category":
            [
                {
                    "scheme":"http://schemas.google.com/g/2005#kind",
                    "term":"http://schemas.google.com/contact/2008#contact"
                }
            ],
            "title":
            {
                "$t":"Marie Curie"
            },
            "content":
            {
                "$t":"Polish-French physicist-chemist who pioneered research on radioactivity"
            },
            "link":
            [
                {
                    "rel":"http://schemas.google.com/contacts/2008/rel#photo",
                    "type":"image/*",
                    "href":"https://www.google.com/m8/feeds/photos/media/test%40example.com/49d4ef73476137d3",
                    "gd$etag":"\"Zh5uNHQASsfwI2A0OE4mdxpcHG0fG2IYVQM.\""
                },
                {
                    "rel":"self",
                    "type":"application/atom+xml",
                    "href":"https://www.google.com/m8/feeds/contacts/test%40example.com/full/49d4ef73476137d3"
                },
                {
                    "rel":"edit",
                    "type":"application/atom+xml",
                    "href":"https://www.google.com/m8/feeds/contacts/test%40example.com/full/49d4ef73476137d3/1319667609985001"
                }
            ],
            "gd$name":
            {
                "gd$fullName":
                {
                    "$t":"Marie Skłodowska Curie"
                },
                "gd$additionalName":
                {
                    "$t":"Skłodowska"
                },
                "gd$givenName":
                {
                    "$t":"Marie"
                },
                "gd$familyName":
                {
                    "$t":"Curie"
                }
            },
            "gContact$nickname":
            {
                "$t":"Marie"
            },
            "gContact$birthday":
            {
                "when":"1867-11-07"
            },
            "gContact$event":
            [
                {
                    "label":"death",
                    "gd$when":
                    {
                        "startTime":"1934-07-04"
                    }
                }
            ],
            "gd$organization":
            [
                {
                    "rel":"http://schemas.google.com/g/2005#work",
                    "gd$orgName":
                    {
                        "$t":"Sorbonne (University of Paris)"
                    },
                    "gd$orgTitle":
                    {
                        "$t":"Physicist-Chemist"
                    }
                }
            ],
            "gd$email":
            [
                {
                    "rel":"http://schemas.google.com/g/2005#home",
                    "address":"mc@example.com",
                    "primary":"true"
                },
                {
                    "rel":"http://schemas.google.com/g/2005#work",
                    "address":"marie.curie@sorbonne.fr"
                }
            ],
            "gd$im":
            [
                {
                    "address":"mariecurie@hotmail.com",
                    "protocol":"http://schemas.google.com/g/2005#MSN",
                    "rel":"http://schemas.google.com/g/2005#other"
                },
                {
                    "address":"mc",
                    "protocol":"http://schemas.google.com/g/2005#AIM",
                    "rel":"http://schemas.google.com/g/2005#other"
                },
                {
                    "address":"marie",
                    "protocol":"http://schemas.google.com/g/2005#YAHOO",
                    "rel":"http://schemas.google.com/g/2005#other"
                },
                {
                    "address":"msc",
                    "protocol":"http://schemas.google.com/g/2005#AIM",
                    "rel":"http://schemas.google.com/g/2005#other"
                },
                {
                    "address":"2424234",
                    "protocol":"http://schemas.google.com/g/2005#ICQ",
                    "rel":"http://schemas.google.com/g/2005#other"
                },
                {
                    "address":"mc",
                    "protocol":"http://schemas.google.com/g/2005#GOOGLE_TALK",
                    "rel":"http://schemas.google.com/g/2005#other"
                }
            ],
            "gd$phoneNumber":
            [
                {
                    "rel":"http://schemas.google.com/g/2005#mobile",
                    "$t":"+33-0-40-46-40-40"
                },
                {
                    "rel":"http://schemas.google.com/g/2005#home_fax",
                    "$t":"+33-0-40-46-20-40"
                },
                {
                    "rel":"http://schemas.google.com/g/2005#home",
                    "$t":"+33-0-40-46-40-41"
                },
                {
                    "rel":"http://schemas.google.com/g/2005#work",
                    "$t":"+33-0-40-46-40-42"
                }
            ],
            "gd$structuredPostalAddress":
            [
                {
                    "rel":"http://schemas.google.com/g/2005#work",
                    "gd$formattedAddress":
                    {
                        "$t":"47, rue des Ecoles\n75230 Paris Cedex 05\nFrance"
                    },
                    "gd$street":
                    {
                        "$t":"47, rue des Ecoles"
                    },
                    "gd$postcode":
                    {
                        "$t":"75230"
                    },
                    "gd$city":
                    {
                        "$t":"Paris"
                    },
                    "gd$region":
                    {
                        "$t":"Cedex 05"
                    },
                    "gd$country":
                    {
                        "code":"FR",
                        "$t":"France"
                    }
                }
            ],
            "gContact$relation":
            [
                {
                    "rel":"father",
                    "$t":"Bronisława Skłodowski"
                },
                {
                    "rel":"mother",
                    "$t":"Władysław Skłodowski"
                },
                {
                    "rel":"spouse",
                    "$t":"Pierre Curie"
                },
                {
                    "rel":"sister",
                    "$t":"Zofia Skłodowski"
                },
                {
                    "rel":"brother",
                    "$t":"Józef Skłodowski"
                },
                {
                    "rel":"brother",
                    "$t":"Bronisława Skłodowski"
                },
                {
                    "rel":"sister",
                    "$t":"Helena Skłodowski"
                },
                {
                    "rel":"child",
                    "$t":"Irène Joliot-Curie"
                },
                {
                    "rel":"child",
                    "$t":"Ève Curie"
                }
            ],
            "gContact$website":
            [
                {
                    "href":"http://www.staff.amu.edu.pl/~zbzw/ph/sci/msc.htm",
                    "rel":"home-page"
                },
                {
                    "href":"http://www.sorbonne.fr/",
                    "rel":"work"
                }
            ],
            "gContact$groupMembershipInfo":
            [
                {
                    "deleted":"false",
                    "href":"http://www.google.com/m8/feeds/groups/test%40example.com/base/d1e92609e11920"
                }
            ]
        }
    }`
    
    
    CONTACT_ALBERT_EINSTEIN = `
    {
        "version":"1.0",
        "encoding":"UTF-8",
        "entry":
        {
            "xmlns":"http://www.w3.org/2005/Atom",
            "xmlns$gContact":"http://schemas.google.com/contact/2008",
            "xmlns$batch":"http://schemas.google.com/gdata/batch",
            "xmlns$gd":"http://schemas.google.com/g/2005",
            "gd$etag":"\"SHczflijLit7I2A9WhdaFksNQQQ.\"",
            "id":
            {
                "$t":"http://www.google.com/m8/feeds/contacts/test%40example.com/base/49d4ef73486137d3"
            },
            "updated":
            {
                "$t":"2011-10-26T22:20:09.985Z"
            },
            "app$edited":
            {
                "xmlns$app":"http://www.w3.org/2007/app",
                "$t":"2011-10-26T22:20:09.985Z"
            },
            "category":
            [
                {
                    "scheme":"http://schemas.google.com/g/2005#kind",
                    "term":"http://schemas.google.com/contact/2008#contact"
                }
            ],
            "title":
            {
                "$t":"Albert Einstein"
            },
            "content":
            {
                "$t":"Developed the Theory of General Relativity"
            },
            "link":
            [
                {
                    "rel":"http://schemas.google.com/contacts/2008/rel#photo",
                    "type":"image/*",
                    "href":"https://www.google.com/m8/feeds/photos/media/test%40example.com/49d4ef73486137d3",
                    "gd$etag":"\"Zh5uNHQASsfwI2A0OE4mdxpcHG0fG2IYVQM.\""
                },
                {
                    "rel":"self",
                    "type":"application/atom+xml",
                    "href":"https://www.google.com/m8/feeds/contacts/test%40example.com/full/49d4ef73486137d3"
                },
                {
                    "rel":"edit",
                    "type":"application/atom+xml",
                    "href":"https://www.google.com/m8/feeds/contacts/test%40example.com/full/49d4ef73486137d3/1319667609985001"
                }
            ],
            "gd$name":
            {
                "gd$fullName":
                {
                    "$t":"Albert Einstein"
                },
                "gd$givenName":
                {
                    "$t":"Albert"
                },
                "gd$familyName":
                {
                    "$t":"Einstein"
                }
            },
            "gContact$nickname":
            {
                "$t":"Albert"
            },
            "gContact$birthday":
            {
                "when":"1879-03-14"
            },
            "gContact$event":
            [
                {
                    "label":"death",
                    "gd$when":
                    {
                        "startTime":"1955-04-18"
                    }
                },
                {
                    "rel":"anniversary",
                    "gd$when":
                    {
                        "startTime":"1919-06-02"
                    }
                }
            ],
            "gd$organization":
            [
                {
                    "rel":"http://schemas.google.com/g/2005#work",
                    "gd$orgName":
                    {
                        "$t":"Institute for Advanced Study"
                    },
                    "gd$orgTitle":
                    {
                        "$t":"Physicist"
                    }
                }
            ],
            "gd$email":
            [
                {
                    "rel":"http://schemas.google.com/g/2005#home",
                    "address":"ae@example.com",
                    "primary":"true"
                },
                {
                    "rel":"http://schemas.google.com/g/2005#work",
                    "address":"albert.einstein@ias.edu"
                }
            ],
            "gd$im":
            [
                {
                    "address":"alberteinstein@hotmail.com",
                    "protocol":"http://schemas.google.com/g/2005#MSN",
                    "rel":"http://schemas.google.com/g/2005#other"
                },
                {
                    "address":"ae",
                    "protocol":"http://schemas.google.com/g/2005#AIM",
                    "rel":"http://schemas.google.com/g/2005#other"
                },
                {
                    "address":"albert",
                    "protocol":"http://schemas.google.com/g/2005#YAHOO",
                    "rel":"http://schemas.google.com/g/2005#other"
                },
                {
                    "address":"potus",
                    "protocol":"http://schemas.google.com/g/2005#AIM",
                    "rel":"http://schemas.google.com/g/2005#other"
                },
                {
                    "address":"45845934",
                    "protocol":"http://schemas.google.com/g/2005#ICQ",
                    "rel":"http://schemas.google.com/g/2005#other"
                },
                {
                    "address":"ae",
                    "protocol":"http://schemas.google.com/g/2005#GOOGLE_TALK",
                    "rel":"http://schemas.google.com/g/2005#other"
                }
            ],
            "gd$phoneNumber":
            [
                {
                    "rel":"http://schemas.google.com/g/2005#mobile",
                    "$t":"+1-609-553-1111"
                },
                {
                    "rel":"http://schemas.google.com/g/2005#home_fax",
                    "$t":"+1-609-553-2222"
                },
                {
                    "rel":"http://schemas.google.com/g/2005#home",
                    "$t":"+1-609-553-3333"
                },
                {
                    "rel":"http://schemas.google.com/g/2005#work",
                    "$t":"+1-609-553-4444"
                }
            ],
            "gd$structuredPostalAddress":
            [
                {
                    "rel":"http://schemas.google.com/g/2005#home",
                    "gd$formattedAddress":
                    {
                        "$t":"Princeton, NJ 08540\nUnited States"
                    },
                    "gd$postcode":
                    {
                        "$t":"08540"
                    },
                    "gd$city":
                    {
                        "$t":"Princeton"
                    },
                    "gd$region":
                    {
                        "$t":"NJ"
                    },
                    "gd$country":
                    {
                        "$t":"United States"
                    }
                },
                {
                    "rel":"http://schemas.google.com/g/2005#work",
                    "gd$formattedAddress":
                    {
                        "$t":"Institute for Advanced Study\nEinstein Drive\nPrinceton, NJ 08540\nUnited States"
                    },
                    "gd$street":
                    {
                        "$t":"Einstein Drive"
                    },
                    "gd$postcode":
                    {
                        "$t":"08540"
                    },
                    "gd$city":
                    {
                        "$t":"Princeton"
                    },
                    "gd$region":
                    {
                        "$t":"NJ"
                    },
                    "gd$country":
                    {
                        "$t":"United States"
                    }
                },
                {
                    "rel":"http://schemas.google.com/g/2005#other",
                    "gd$formattedAddress":
                    {
                        "$t":"Princeton, NJ\nUSA"
                    },
                    "gd$city":
                    {
                        "$t":"Princeton"
                    },
                    "gd$region":
                    {
                        "$t":"NJ"
                    },
                    "gd$country":
                    {
                        "code":"US",
                        "$t":"USA"
                    }
                }
            ],
            "gContact$relation":
            [
                {
                    "rel":"father",
                    "$t":"Hermann Einstein"
                },
                {
                    "rel":"mother",
                    "$t":"Pauline Einstein"
                },
                {
                    "rel":"spouse",
                    "$t":"Elsa Löwenthal"
                },
                {
                    "rel":"child",
                    "$t":"Hans Albert Einstein"
                },
                {
                    "rel":"child",
                    "$t":"Eduard Einstein"
                }
            ],
            "gContact$website":
            [
                {
                    "href":"http://en.wikipedia.org/wiki/Albert_Einstein",
                    "rel":"home-page"
                },
                {
                    "href":"http://www.ias.edu",
                    "rel":"work"
                }
            ],
            "gContact$groupMembershipInfo":
            [
                {
                    "deleted":"false",
                    "href":"http://www.google.com/m8/feeds/groups/test%40example.com/base/d1e92609e11920"
                }
            ]
        }
    }`

    EXISTING_GROUPS = `
    [
        {
            "description":"College Friends",
            "name":"College Friends",
            "user_id":"testname"
        },
        {
            "description":"Acquaintances",
            "name":"Acquaintances",
            "user_id":"testname"
        },
        {
            "description":"Business Leaders",
            "name":"Business Leaders",
            "user_id":"testname"
        },
        {
            "description":"Historians",
            "name":"Historians",
            "user_id":"testname"
        },
        {
            "description":"Technologists",
            "name":"Technologists",
            "user_id":"testname"
        },
        {
            "description":"Generals",
            "name":"Generals",
            "user_id":"testname"
        },
        {
            "description":"Scientists",
            "name":"Scientists",
            "user_id":"testname"
        },
        {
            "description":"Anarchists",
            "name":"Anarchists",
            "user_id":"testname"
        },
        {
            "description":"Friends",
            "name":"Friends",
            "user_id":"testname"
        },
        {
            "description":"Family",
            "name":"Family",
            "user_id":"testname"
        }
    ]`
    
    
    EXISTING_CONTACTS = `
    [
        {
            "anniversary":
            {
                "day":25,
                "month":10,
                "year":1764
            },
            "birthday":
            {
                "day":30,
                "month":10,
                "year":1735
            },
            "company":"United States of America Federal Government",
            "dates":
            [
                {
                    "label":"death",
                    "value":
                    {
                        "day":4,
                        "month":7,
                        "year":1826
                    }
                },
                {
                    "rel":"anniversary",
                    "value":
                    {
                        "day":25,
                        "month":10,
                        "year":1764
                    }
                }
            ],
            "display_name":"John Adams",
            "email_addresses":
            [
                {
                    "email_address":"ja@example.com",
                    "is_primary":true,
                    "rel":"home"
                },
                {
                    "email_address":"john.adams@whitehouse.gov",
                    "rel":"work"
                },
                {
                    "email_address":"potus@whitehouse.gov",
                    "label":"Old Work"
                }
            ],
            "given_name":"John",
            "ims":
            [
                {
                    "handle":"john_adams@hotmail.com",
                    "protocol":"msn",
                    "rel":"other"
                },
                {
                    "handle":"ja",
                    "protocol":"aim",
                    "rel":"other"
                },
                {
                    "handle":"john",
                    "protocol":"yahoo_messenger",
                    "rel":"other"
                },
                {
                    "handle":"potus",
                    "protocol":"aim",
                    "rel":"other"
                },
                {
                    "handle":"12467",
                    "protocol":"icq",
                    "rel":"other"
                },
                {
                    "handle":"ja",
                    "protocol":"google_talk",
                    "rel":"other"
                }
            ],
            "nickname":"John",
            "notes":"2nd President of the US",
            "phone_numbers":
            [
                {
                    "area_code":"202",
                    "country_code":"1",
                    "formatted_number":"+1-202-554-1111",
                    "local_phone_number":"554-1111",
                    "rel":"mobile"
                },
                {
                    "area_code":"202",
                    "country_code":"1",
                    "formatted_number":"+1-202-554-2222",
                    "local_phone_number":"554-2222",
                    "rel":"home_fax"
                },
                {
                    "area_code":"202",
                    "country_code":"1",
                    "formatted_number":"+1-202-554-3333",
                    "local_phone_number":"554-3333",
                    "rel":"home"
                },
                {
                    "area_code":"202",
                    "country_code":"1",
                    "formatted_number":"+1-202-554-6666",
                    "local_phone_number":"554-6666",
                    "rel":"work"
                }
            ],
            "postal_addresses":
            [
                {
                    "address":"1600 Pennsylvania Ave\nWashington, DC 20500\nUnited States",
                    "country":"United States",
                    "is_current":false,
                    "municipality":"Washington",
                    "postal_code":"20500",
                    "region":"DC",
                    "rel":"work",
                    "street_address":"1600 Pennsylvania Ave"
                },
                {
                    "address":"Quincy, MA\nUSA",
                    "country":"USA",
                    "is_current":true,
                    "municipality":"Quincy",
                    "region":"MA",
                    "rel":"other"
                }
            ],
            "primary_address":"Quincy, MA\nUSA",
            "primary_email":"ja@example.com",
            "primary_im":"msn:johnadams@hotmail.com",
            "primary_phone_number":"+1-202-554-1111",
            "relationships":
            [
                {
                    "contact_reference_name":"John Adams, Sr.",
                    "rel":"father"
                },
                {
                    "contact_reference_name":"Susanna Boylston Adams",
                    "rel":"mother"
                },
                {
                    "contact_reference_name":"Abigail Smith",
                    "rel":"spouse"
                }
            ],
            "surname":"Adams",
            "title":"President of the United States",
            "uris":
            [
                {
                    "rel":"homepage",
                    "uri":"http://www.whitehouse.gov/about/presidents/johnadams"
                }
            ],
            "user_id":"testname"
        },
        {
            "birthday":
            {
                "day":22,
                "month":2,
                "year":1732
            },
            "company":"United States of America",
            "dates":
            [
                {
                    "label":"death",
                    "value":
                    {
                        "day":14,
                        "month":12,
                        "year":1799
                    }
                }
            ],
            "display_name":"George Washington",
            "email_addresses":
            [
                {
                    "email_address":"gw@example.com",
                    "is_primary":true,
                    "rel":"home"
                },
                {
                    "email_address":"george-washington@whitehouse.gov",
                    "rel":"work"
                },
                {
                    "email_address":"potus@whitehouse.gov",
                    "label":"Old Work"
                }
            ],
            "given_name":"George",
            "ims":
            [
                {
                    "handle":"george.washington@hotmail.com",
                    "protocol":"msn",
                    "rel":"other"
                },
                {
                    "handle":"gw",
                    "protocol":"aim",
                    "rel":"other"
                },
                {
                    "handle":"george",
                    "protocol":"yahoo_messenger",
                    "rel":"other"
                },
                {
                    "handle":"potus",
                    "protocol":"aim",
                    "rel":"other"
                },
                {
                    "handle":"12432",
                    "protocol":"icq",
                    "rel":"other"
                },
                {
                    "handle":"gw",
                    "protocol":"google_talk",
                    "rel":"other"
                }
            ],
            "nickname":"George",
            "notes":"1st President of the US\nCommander in the Revolutionary War",
            "phone_numbers":
            [
                {
                    "area_code":"202",
                    "country_code":"1",
                    "formatted_number":"+1-202-555-1111",
                    "local_phone_number":"555-1111",
                    "rel":"mobile"
                },
                {
                    "area_code":"202",
                    "country_code":"1",
                    "formatted_number":"+1-202-555-5555",
                    "local_phone_number":"555-5555",
                    "rel":"home_fax"
                },
                {
                    "area_code":"202",
                    "country_code":"1",
                    "formatted_number":"+1-202-555-3333",
                    "local_phone_number":"555-3333",
                    "rel":"home"
                },
                {
                    "area_code":"202",
                    "country_code":"1",
                    "formatted_number":"+1-202-555-4444",
                    "local_phone_number":"555-4444",
                    "rel":"work"
                }
            ],
            "postal_addresses":
            [
                {
                    "address":"524-30 Market Street\nPhiladelphia, PA 19106\nUnited States",
                    "country":"United States",
                    "is_current":false,
                    "municipality":"Philadelphia",
                    "postal_code":"19106",
                    "region":"PA",
                    "rel":"work",
                    "street_address":"524-30 Market Street"
                },
                {
                    "address":"Mount Vernon, VA\nUSA",
                    "country":"USA",
                    "is_current":true,
                    "municipality":"Mount Vernon",
                    "region":"VA",
                    "rel":"other"
                }
            ],
            "primary_address":"Mount Vernon, VA\nUSA",
            "primary_email":"gw@example.com",
            "primary_im":"msn:georgewashington@hotmail.com",
            "primary_phone_number":"+1-202-555-1111",
            "relationships":
            [
                {
                    "contact_reference_name":"Augustine Washington",
                    "rel":"father"
                },
                {
                    "contact_reference_name":"Mary Ball Washington",
                    "rel":"mother"
                },
                {
                    "contact_reference_name":"Mildred Washington",
                    "rel":"sister"
                },
                {
                    "contact_reference_name":"Butler Washington",
                    "rel":"brother"
                },
                {
                    "contact_reference_name":"Lawrence Washington",
                    "rel":"brother"
                },
                {
                    "contact_reference_name":"Charles Washington",
                    "rel":"brother"
                }
            ],
            "surname":"Washington",
            "title":"President of the United States",
            "uris":
            [
                {
                    "rel":"homepage",
                    "uri":"http://www.whitehouse.gov/about/presidents/georgewashington"
                }
            ],
            "user_id":"testname"
        }
    ]`
    
)

var (
    GOOGLE_USERINFO_RESULT oauth2_client.GoogleUserInfoResult
)


func init() {
    GOOGLE_USERINFO_RESULT = oauth2_client.NewGoogleUserInfoResult("test@example.com", "John", "test@example.com", "https://www.google.com/m8/feeds/contacts/test%40example.com/full", time.UTC())
}

func TestInitialSyncWithEmptyDataStoreWithGoogleContacts(t *testing.T) {
    pipeline := new(contacts.Pipeline)
    mockClient := google.NewMockGoogleClient()
    mockClient.AddMockGroupJSONFeed(GROUPS_ALL)
    mockClient.AddMockContactJSONEntry(CONTACT_GEORGE_WASHINGTON)
    mockClient.AddMockContactJSONEntry(CONTACT_JOHN_ADAMS)
    mockClient.AddMockContactJSONEntry(CONTACT_MARIE_CURIE)
    mockClient.AddMockContactJSONEntry(CONTACT_ALBERT_EINSTEIN)
    mockClient.SetRetrieveUserInfo(GOOGLE_USERINFO_RESULT, nil)
    ds := datastore.NewInMemoryDataStore()
    cs := contacts.NewGoogleContactService()
    dsocialUserId := "testname"
    csSettings := contacts.NewGoogleContactServiceSettings()
    csSettings.SetId("ABC-123")
    csSettings.SetDsocialUserId(dsocialUserId)
    csSettings.SetClientProperties(make(jsonhelper.JSONObject))
    csSettings.SetExternalUserId("test@example.com")
    pipeline.InitialSync(mockClient, ds, cs, csSettings, dsocialUserId, "me-contact-id")
    buf := bytes.NewBuffer(make([]byte, 0))
    ds.Encode(buf)
    t.Fatalf("Final data store is:\n%s\n\n", buf.String())
}

func TestInitialSyncWithPartialDataStoreWithGoogleContacts(t *testing.T) {
    pipeline := new(contacts.Pipeline)
    mockClient := google.NewMockGoogleClient()
    mockClient.AddMockGroupJSONFeed(GROUPS_ALL)
    mockClient.AddMockContactJSONEntry(CONTACT_GEORGE_WASHINGTON)
    mockClient.AddMockContactJSONEntry(CONTACT_JOHN_ADAMS)
    mockClient.AddMockContactJSONEntry(CONTACT_MARIE_CURIE)
    mockClient.AddMockContactJSONEntry(CONTACT_ALBERT_EINSTEIN)
    mockClient.SetRetrieveUserInfo(GOOGLE_USERINFO_RESULT, nil)
    ds := datastore.NewInMemoryDataStore()
    cs := contacts.NewGoogleContactService()
    dsocialUserId := "testname"
    csSettings := contacts.NewGoogleContactServiceSettings()
    csSettings.SetId("ABC-123")
    csSettings.SetDsocialUserId(dsocialUserId)
    csSettings.SetClientProperties(make(jsonhelper.JSONObject))
    csSettings.SetExternalUserId("test@example.com")
    existingGroups := make([]*dm.Group, 0)
    if err := json.Unmarshal([]byte(EXISTING_GROUPS), &existingGroups); err != nil {
        t.Fatalf("Unable to parse EXISTING_GROUPS: %s\n\n", err.String())
    }
    for _, group := range existingGroups {
        ds.StoreDsocialGroup(dsocialUserId, "", group)
    }
    existingContacts := make([]*dm.Contact, 0)
    if err := json.Unmarshal([]byte(EXISTING_CONTACTS), &existingContacts); err != nil {
        t.Fatalf("Unable to parse EXISTING_CONTACTS: %s\n\n", err.String())
    }
    for _, contact := range existingContacts {
        t.Logf("%s => %#v", contact.DisplayName, contact)
        ds.StoreDsocialContact(dsocialUserId, "", contact)
    }
    pipeline.InitialSync(mockClient, ds, cs, csSettings, dsocialUserId, "me-contact-id")
    buf := bytes.NewBuffer(make([]byte, 0))
    ds.Encode(buf)
    t.Fatalf("Final data store is:\n%s\n\n", buf.String())
}


