include $(GOROOT)/src/Make.inc

TARG=github.com/pomack/dsocial.go/backend/contacts
GOFILES=\
	google.go\
	googleplus.go\
	linkedin.go\
	pipeline.go\
	service.go\
	smugmug.go\
	twitter.go\
	yahoo.go


include $(GOROOT)/src/Make.pkg

check:
	gomake test


