include $(GOROOT)/src/Make.inc

TARG=github.com/pomack/dsocial.go/api/apiutil
GOFILES=\
	const.go\
	escape.go\
	jsonmediatypehandler.go\
	jsonmediatypeinputhandler.go\
	outpututil.go\
	signer.go\


include $(GOROOT)/src/Make.pkg

check:
	gomake test


