include $(GOROOT)/src/Make.inc

TARG=github.com/pomack/dsocial.go/api/apiutil
GOFILES=\
	jsonmediatypehandler.go\
	jsonmediatypeinputhandler.go\


include $(GOROOT)/src/Make.pkg

check:
	gomake test


