include $(GOROOT)/src/Make.inc

TARG=github.com/pomack/dsocial.go/models/dsocial
GOFILES=\
	accounts.go\
	albums.go\
	audio.go\
	authentication.go\
	authorization.go\
	changes.go\
	compare.go\
	const.go\
	contacts.go\
	convert_facebook.go\
	convert_google.go\
	convert_googleplus.go\
	convert_linkedin.go\
	convert_smugmug.go\
	convert_twitter.go\
	convert_yahoo.go\
	images.go\
	util.go


include $(GOROOT)/src/Make.pkg

check:
	gomake test


