include $(GOROOT)/src/Make.inc

TARG=github.com/pomack/dsocial.go/api/contacts
GOFILES=\
	delete.go\
	edit.go\
	list.go\
	new.go\
	search.go\
	update.go\
	view.go


include $(GOROOT)/src/Make.pkg

check:
	gomake test


