include $(GOROOT)/src/Make.inc

TARG=github.com/pomack/dsocial.go/api/external_services
GOFILES=\
	create.go\
	edit.go\
	list.go\
	new.go\
	update.go\
	view.go


include $(GOROOT)/src/Make.pkg

check:
	gomake test


