package inmemory

const (
    _INMEMORY_USER_ACCOUNT_COLLECTION_NAME                              = "user_accounts"
    _INMEMORY_USER_ACCOUNT_ID_FOR_USERNAME_COLLECTION_NAME              = "user_account_id_for_username"
    _INMEMORY_USER_ACCOUNT_ID_FOR_EMAIL_COLLECTION_NAME                 = "user_account_id_for_email"
    _INMEMORY_CONSUMER_ACCOUNT_COLLECTION_NAME                          = "consumer_accounts"
    _INMEMORY_CONSUMER_ACCOUNT_ID_FOR_SHORTNAME_COLLECTION_NAME         = "consumer_account_id_for_shortname"
    _INMEMORY_CONSUMER_ACCOUNT_IDS_FOR_NAME_COLLECTION_NAME             = "consumer_account_ids_for_name"
    _INMEMORY_CONSUMER_ACCOUNT_IDS_FOR_DOMAIN_NAME_COLLECTION_NAME      = "consumer_account_ids_for_domain_name"
    _INMEMORY_EXTERNAL_USER_ACCOUNT_COLLECTION_NAME                     = "external_user_accounts"
    _INMEMORY_EXTERNAL_ACCOUNT_IDS_FOR_CONSUMER_ID_COLLECTION_NAME      = "external_account_ids_for_consumer_id"
    _INMEMORY_EXTERNAL_ACCOUNT_IDS_FOR_EXTERNAL_USER_ID_COLLECTION_NAME = "external_account_ids_for_external_user_id"

    _INMEMORY_USER_PASSWORD_COLLECTION_NAME                 = "user_passwords"
    _INMEMORY_ACCESS_KEYS_COLLECTION_NAME                   = "access_keys"
    _INMEMORY_ACCESS_KEYS_FOR_USER_ID_COLLECTION_NAME       = "access_keys_for_user_id"
    _INMEMORY_ACCESS_KEYS_FOR_CONSUMER_ID_COLLECTION_NAME   = "access_keys_for_consumer_id"

    _INMEMORY_SESSIONS_COLLECTION_NAME                            = "sessions"
    _INMEMORY_SESSION_IDS_FOR_USER_ID_COLLECTION_NAME             = "session_ids_for_user_id"
    _INMEMORY_SESSION_IDS_FOR_CONSUMER_ID_COLLECTION_NAME         = "session_ids_for_consumer_id"
    _INMEMORY_SESSION_IDS_FOR_EXTERNAL_USER_ID_COLLECTION_NAME    = "session_ids_for_external_user_id"
    _INMEMORY_AUTH_TOKENS_COLLECTION_NAME                         = "auth_tokens"
    _INMEMORY_AUTH_TOKEN_IDS_FOR_USER_ID_COLLECTION_NAME          = "auth_token_ids_for_user_id"
    _INMEMORY_AUTH_TOKEN_IDS_FOR_CONSUMER_ID_COLLECTION_NAME      = "auth_token_ids_for_consumer_id"
    _INMEMORY_AUTH_TOKEN_IDS_FOR_EXTERNAL_USER_ID_COLLECTION_NAME = "auth_token_ids_for_external_user_id"

    _INMEMORY_CONTACT_COLLECTION_NAME                              = "contacts"
    _INMEMORY_CONNECTION_COLLECTION_NAME                           = "connections"
    _INMEMORY_GROUP_COLLECTION_NAME                                = "group"
    _INMEMORY_CHANGESET_COLLECTION_NAME                            = "changesets"
    _INMEMORY_EXTERNAL_CONTACT_COLLECTION_NAME                     = "external_contacts"
    _INMEMORY_EXTERNAL_GROUP_COLLECTION_NAME                       = "external_group"
    _INMEMORY_CONTACT_FOR_EXTERNAL_CONTACT_COLLECTION_NAME         = "contacts_for_external_contacts"
    _INMEMORY_GROUP_FOR_EXTERNAL_GROUP_COLLECTION_NAME             = "groups_for_external_group"
    _INMEMORY_EXTERNAL_TO_INTERNAL_CONTACT_MAPPING_COLLECTION_NAME = "external_to_internal_contact_mappings"
    _INMEMORY_INTERNAL_TO_EXTERNAL_CONTACT_MAPPING_COLLECTION_NAME = "internal_to_external_contact_mappings"
    _INMEMORY_EXTERNAL_TO_INTERNAL_GROUP_MAPPING_COLLECTION_NAME   = "external_to_internal_group_mappings"
    _INMEMORY_INTERNAL_TO_EXTERNAL_GROUP_MAPPING_COLLECTION_NAME   = "internal_to_external_group_mappings"
    _INMEMORY_USER_TO_CONTACT_SETTINGS_COLLECTION_NAME             = "user_to_contact_settings"
    _INMEMORY_CHANGESETS_TO_APPLY_COLLECTION_NAME                  = "changesets_to_apply"
    _INMEMORY_CHANGESETS_NOT_CURRENTLY_APPLYABLE_COLLECTION_NAME   = "changesets_not_currently_applyable"
)
