include $(GOROOT)/src/Make.inc

TARG=github.com/pomack/dsocial.go/api/account
GOFILES=\
	create.go\
	delete.go\
	disable.go\
	update.go\
	view.go


include $(GOROOT)/src/Make.pkg

check:
	gomake test


